# To build mingw projects which use fairly new cmake

FROM debian:9-slim
MAINTAINER Anton Krug <anton.krug@microsemi.com>

RUN wget -nv --no-check-certificate https://github.com/AntonKrug/ead/releases/download/v0.5.1/ead-linux-x86-64-20190715-181821 -O /bin/ead

VOLUME /docker_shares/common

